# Generated by Django 4.2.30 on 2026-07-15 15:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('plan', models.CharField(default='free', max_length=20)),
                ('role', models.CharField(default='user', max_length=10)),
                ('status', models.CharField(default='active', max_length=12)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('auth_provider', models.CharField(default='local', max_length=10)),
                ('google_sub', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('session_token', models.CharField(blank=True, max_length=32, null=True)),
                ('ban_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('predictions_today', models.IntegerField(default=0)),
                ('last_prediction_date', models.DateField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=64, null=True)),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('pro_expires_at', models.DateField(blank=True, null=True)),
                ('theme_preference', models.CharField(default='system', max_length=10)),
                ('ai_analyses_today', models.IntegerField(default=0)),
                ('last_ai_analysis_date', models.DateField(blank=True, null=True)),
                ('backtests_today', models.IntegerField(default=0)),
                ('last_backtest_date', models.DateField(blank=True, null=True)),
                ('xp', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('paper_trading_opted_in', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(db_index=True, default='error', max_length=10)),
                ('endpoint', models.CharField(blank=True, max_length=120, null=True)),
                ('method', models.CharField(blank=True, max_length=8, null=True)),
                ('message', models.CharField(max_length=500)),
                ('trace', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(db_index=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=40, null=True)),
                ('ticker', models.CharField(db_index=True, max_length=12)),
                ('asset_class', models.CharField(max_length=12)),
                ('side', models.CharField(max_length=5)),
                ('qty', models.FloatField()),
                ('entry_time', models.DateTimeField()),
                ('entry_price', models.FloatField()),
                ('entry_mkt', models.FloatField()),
                ('price_source', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_price', models.FloatField()),
                ('target_price', models.FloatField()),
                ('max_hold_hours', models.IntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('rationale', models.CharField(blank=True, max_length=300, null=True)),
                ('commission', models.FloatField(default=0.0)),
                ('status', models.CharField(db_index=True, default='open', max_length=8)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_mkt', models.FloatField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=12, null=True)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_trade',
            },
        ),
        migrations.CreateModel(
            name='PythFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12, unique=True)),
                ('feed_id', models.CharField(max_length=70)),
                ('pyth_symbol', models.CharField(blank=True, max_length=40, null=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'pyth_feed',
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'resource_link',
            },
        ),
        migrations.CreateModel(
            name='TickerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'ticker_config',
            },
        ),
        migrations.CreateModel(
            name='TradingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('asset_class', models.CharField(blank=True, max_length=20, null=True)),
                ('interval', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'trading_bot',
            },
        ),
        migrations.CreateModel(
            name='UserPaperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_balance', models.FloatField(default=10000.0)),
                ('balance', models.FloatField(default=10000.0)),
                ('equity', models.FloatField(default=10000.0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_paper_account',
            },
        ),
        migrations.CreateModel(
            name='WhatsappConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_config',
            },
        ),
        migrations.CreateModel(
            name='UserWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(default='My Webhook', max_length=50)),
                ('events', models.CharField(blank=True, max_length=100, null=True)),
                ('secret', models.CharField(blank=True, max_length=32, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_fired', models.DateTimeField(blank=True, null=True)),
                ('fire_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_webhook',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_enabled', models.BooleanField(default=False)),
                ('theme', models.CharField(default='dark', max_length=10)),
                ('default_ticker', models.CharField(default='AAPL', max_length=12)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('risk_intro_seen', models.BooleanField(default=False)),
                ('usage_notice_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity', models.FloatField()),
                ('balance', models.FloatField()),
                ('open_positions', models.IntegerField(default=0)),
                ('snapshot_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_portfolio',
            },
        ),
        migrations.CreateModel(
            name='UserPaperPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('side', models.CharField(max_length=5)),
                ('quantity', models.FloatField()),
                ('entry_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('sl', models.FloatField(blank=True, null=True)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('realized_pnl', models.FloatField(default=0.0)),
                ('status', models.CharField(default='open', max_length=10)),
                ('opened_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='users.userpaperaccount')),
            ],
            options={
                'db_table': 'user_paper_position',
            },
        ),
        migrations.CreateModel(
            name='UserPaperOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('order_type', models.CharField(max_length=10)),
                ('side', models.CharField(max_length=5)),
                ('quantity', models.FloatField()),
                ('target_price', models.FloatField(blank=True, null=True)),
                ('sl', models.FloatField(blank=True, null=True)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=15)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='users.userpaperaccount')),
            ],
            options={
                'db_table': 'user_paper_order',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('backup_codes', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'two_factor_auth',
            },
        ),
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, max_length=12, null=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('mood', models.CharField(blank=True, max_length=10, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('trade_type', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_journal',
            },
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_config',
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('price', models.FloatField()),
                ('direction', models.CharField(max_length=8)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_alert',
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('interval', models.CharField(max_length=4)),
                ('current_price', models.FloatField()),
                ('lr_pred', models.FloatField()),
                ('rf_pred', models.FloatField()),
                ('direction', models.CharField(max_length=8)),
                ('confidence', models.FloatField()),
                ('predicted_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('src_source', models.CharField(blank=True, max_length=12, null=True)),
                ('src_conf_pct', models.FloatField(blank=True, null=True)),
                ('src_divergence', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prediction_history',
            },
        ),
        migrations.CreateModel(
            name='PredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('direction_ok', models.BooleanField(blank=True, null=True)),
                ('pct_error', models.FloatField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('prediction', models.ForeignKey(db_column='prediction_id', on_delete=django.db.models.deletion.CASCADE, to='users.predictionhistory')),
            ],
            options={
                'db_table': 'prediction_accuracy',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('side', models.CharField(max_length=8)),
                ('entry_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=8)),
                ('opened_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_position',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=10)),
                ('plan', models.CharField(blank=True, max_length=10, null=True)),
                ('tier', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('reference', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('receipt', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('flagged', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_token',
            },
        ),
        migrations.CreateModel(
            name='PaperTradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
                ('detail', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('trade', models.ForeignKey(blank=True, db_column='trade_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.papertrade')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_trade_event',
            },
        ),
        migrations.CreateModel(
            name='PaperEquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(db_index=True, max_length=20)),
                ('equity', models.FloatField()),
                ('open_count', models.IntegerField(default=0)),
                ('taken_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_equity_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='info', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(blank=True, max_length=300, null=True)),
                ('read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=12)),
                ('model_type', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=16)),
                ('file_path', models.CharField(max_length=256)),
                ('metrics_json', models.TextField(blank=True, null=True)),
                ('feature_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('data_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('trained_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'model_version',
                'unique_together': {('ticker', 'model_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('days', models.IntegerField(default=30)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('used_by', models.ForeignKey(blank=True, db_column='used_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gift_code',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='DiscordConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.CharField(max_length=400)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discord_config',
            },
        ),
        migrations.CreateModel(
            name='CompetitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_balance', models.FloatField(default=10000.0)),
                ('status', models.CharField(default='upcoming', max_length=12)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competition_model',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('segment', models.CharField(default='all', max_length=10)),
                ('channel', models.CharField(default='in-app', max_length=10)),
                ('sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast',
            },
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_setting',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(default='Default', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('calls_today', models.IntegerField(default=0)),
                ('calls_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=30, null=True)),
                ('target_id', models.CharField(blank=True, max_length=40, null=True)),
                ('detail', models.CharField(blank=True, max_length=400, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_audit_log',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('ua', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('added_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist_item',
                'unique_together': {('user', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('added_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist',
                'unique_together': {('user', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='UserBotSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('bot', models.ForeignKey(db_column='bot_id', on_delete=django.db.models.deletion.CASCADE, to='users.tradingbot')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_bot_subscription',
                'unique_together': {('user', 'bot')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(max_length=32)),
                ('earned_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievement',
                'unique_together': {('user', 'achievement_id')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_equity', models.FloatField()),
                ('current_equity', models.FloatField()),
                ('joined_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('competition', models.ForeignKey(db_column='competition_id', on_delete=django.db.models.deletion.CASCADE, to='users.competitionmodel')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competition_entry',
                'unique_together': {('competition', 'user')},
            },
        ),
    ]
